// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/marketplace-layouts/EditorialGrid.tsx": () => import("../components/mockups/marketplace-layouts/EditorialGrid.tsx"),
  "./components/mockups/marketplace-layouts/HorizontalDensity.tsx": () => import("../components/mockups/marketplace-layouts/HorizontalDensity.tsx"),
  "./components/mockups/marketplace-layouts/VerticalFlow.tsx": () => import("../components/mockups/marketplace-layouts/VerticalFlow.tsx")
};
