// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pubg-marketplace/CleanLight.tsx": () => import("../components/mockups/pubg-marketplace/CleanLight.tsx"),
  "./components/mockups/pubg-marketplace/HybridDarkOrange.tsx": () => import("../components/mockups/pubg-marketplace/HybridDarkOrange.tsx"),
  "./components/mockups/pubg-marketplace/PremiumCardHeavy.tsx": () => import("../components/mockups/pubg-marketplace/PremiumCardHeavy.tsx")
};
